const $=s=>document.querySelector(s);let session=null;const messages=[];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const money=v=>`¥${Number(v).toLocaleString("zh-CN",{maximumFractionDigits:0})}`;
const hm=v=>new Date(v).toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit",hour12:false});
const dateLabel=v=>new Date(`${v}T00:00:00`).toLocaleDateString("zh-CN",{month:"short",day:"numeric",weekday:"short"});
const badge=s=>`<span class="source-badge ${esc(s?.status)}">${esc(s?.status||"UNKNOWN")} · ${esc(s?.provider||"unknown")}</span>`;
async function api(url,options={}){const r=await fetch(url,{headers:{"Content-Type":"application/json"},...options});const d=await r.json();if(!r.ok){const detail=d.detail,err=new Error(typeof detail==="string"?detail:detail?.message||"请求失败");err.detail=detail;throw err}return d}
function setStatus(text){$("#status").textContent=text}
function showProgress(active=5){const labels=["理解需求","冻结数据","生成候选","约束验证","准备交互"];$("#progress").classList.remove("hidden");$("#progress").innerHTML=labels.map((x,i)=>`<span class="${i<active?"done":""}">${i+1}. ${x}</span>`).join("")}

async function loadHealth(){try{const[h,r]=await Promise.all([api("/health"),api("/readiness")]);const llm=h.llm_enabled?`LLM · ${h.llm_model}`:"DETERMINISTIC";const live=r.live_ready?`LIVE READY · ${r.provider_ready_count}/${r.provider_total_count}`:"DEMO READY · LIVE DEGRADED";$("#systemMode").textContent=`${llm} · ${live}`;$(".system-badge").classList.toggle("degraded",!r.live_ready);$(".system-badge").title=r.checks.filter(x=>x.status!=="PASS").map(x=>`${x.label}: ${x.detail}`).join("\n")}catch{$("#systemMode").textContent="LOCAL DEMO"}}
$("#scenario").addEventListener("change",e=>{if(e.target.value)$("#request").value=e.target.value});
$("#create").addEventListener("click",async()=>{const mode=$("#dataMode").value;setStatus(mode==="LIVE"?"正在并发查询实时 MCP 并冻结快照…":"正在解析约束并生成同源方案…");showProgress(2);try{const d=await api("/v2/sessions",{method:"POST",body:JSON.stringify({text:$("#request").value,mode})});if(d.status==="NEEDS_INPUT"){setStatus(d.questions.join(" "));return}session=d;showProgress(5);messages.length=0;messages.push({role:"agent",text:`${mode==="LIVE"?"实时":"演示"}快照与三个方案已经生成。先选择一个，我们再继续调整。`});render();setStatus("三个方案已经通过约束检查")}catch(e){renderConflict(e.detail);setStatus(e.message)}});

function planCard(p,i){const t=p.itinerary,selected=session.selected_index===i;return `<article class="card ${selected?"selected":""}"><p class="tag">方案 ${i} · ${["预算优先","均衡推荐","时间优先"][i-1]}</p><div class="route">${esc(t.outbound.mode)} 去 · ${esc(t.inbound.mode)} 回</div><p class="price">${money(t.budget.total_cny)}</p><p class="meta">${esc(t.lodging_area.name)}<br>${t.days.reduce((n,d)=>n+d.visits.length,0)} 个景点 · ${p.validation.feasible?"✓ 约束通过":"需调整"}</p><button class="primary" data-select="${i}">${selected?"当前方案":"选择此方案"}</button></article>`}
function render(){if(!session)return;$("#choiceSection").classList.remove("hidden");$("#alternatives").innerHTML=session.alternatives.alternatives.map((p,i)=>planCard(p,i+1)).join("");document.querySelectorAll("[data-select]").forEach(b=>b.onclick=()=>selectPlan(Number(b.dataset.select)));renderSnapshot();if(session.selected_plan){$("#workspace").classList.remove("hidden");renderPlan(session.selected_plan);renderChat();renderRuntime()}else{$("#workspace").classList.add("hidden")}document.querySelectorAll(".locks input").forEach(x=>x.checked=session.locked_fields.includes(x.value));$("#refresh").disabled=session.mode!=="LIVE"}
async function selectPlan(i){try{session=await api(`/v2/sessions/${session.id}/select`,{method:"POST",body:JSON.stringify({index:i})});messages.push({role:"user",text:`选择方案 ${i}`},{role:"agent",text:"方案已选中。你可以锁定满意部分，或继续用自然语言调整。"});render()}catch(e){setStatus(e.message)}}

function renderPlan(p){const t=p.itinerary;$("#planTitle").textContent=t.title;const transport=(x,icon,label)=>`<div class="overview-card"><span class="icon">${icon}</span><strong>${label} · ${esc(x.label)}</strong><small>${hm(x.depart_at)} → ${hm(x.arrive_at)} · ${x.duration_minutes} 分钟<br>${money(x.price_per_person_cny)}/人</small>${badge(x.source)}</div>`;$("#overview").innerHTML=transport(t.outbound,"↗","去程")+transport(t.inbound,"↙","返程")+`<div class="overview-card"><span class="icon">⌂</span><strong>${esc(t.lodging_area.name)}</strong><small>${money(t.lodging_area.nightly_price_estimate_cny)}/晚 · ${esc(t.lodging_area.price_basis)}<br>${esc(t.lodging_area.description)}</small>${badge(t.lodging_area.source)}</div>`;renderDays(t);renderBudget(t.budget);renderSources(p);renderMap(t);}
function renderDays(t){let count=0;$("#days").innerHTML=t.days.map((d,i)=>{count+=d.visits.length;return `<section class="day"><div class="day-date"><strong>DAY ${i+1}</strong><span>${dateLabel(d.date)}<br>市内交通 ${money(d.local_transport_cost_cny)}</span></div><div class="visits">${d.visits.length?d.visits.map(v=>`<div class="visit"><time>${hm(v.start_at)}<br><small>${hm(v.end_at)}</small></time><div class="visit-info"><strong>${esc(v.place_name)}</strong><small>${esc(v.route_from_previous.mode)} · ${v.route_from_previous.minutes} 分钟 · ${v.route_from_previous.distance_km} km · 门票 ${money(v.admission_total_cny)}</small><br>${badge(v.source)}</div><button class="replace" data-replace="${esc(v.place_id)}">替换</button></div>`).join(""):"<p class='muted'>无已安排景点</p>"}</div></section>`}).join("");$("#visitCount").textContent=`${count} 个景点`;document.querySelectorAll("[data-replace]").forEach(b=>b.onclick=()=>replacePlace(b.dataset.replace))}
async function replacePlace(id){try{messages.push({role:"user",text:"替换这个景点"});session=await api(`/v2/sessions/${session.id}/places/replace`,{method:"POST",body:JSON.stringify({place_id:id})});messages.push({role:"agent",text:"景点已替换，其余已确认交通与住宿保持不变。"});clearConflict();render()}catch(e){renderConflict(e.detail);messages.push({role:"agent",text:e.message});renderChat()}}
function renderBudget(b){const rows=[["往返交通",b.transport_cny],["住宿",b.lodging_cny],["门票",b.admission_cny],["市内交通",b.local_transport_cny],["餐饮估算",b.meals_estimated_cny]],total=Number(b.total_cny)||1;$("#budgetTotal").textContent=money(total);$("#budget").innerHTML=rows.map(([n,v])=>`<div class="budget-row"><span>${n}</span><div class="bar"><i style="width:${Math.max(2,Number(v)/total*100)}%"></i></div><strong>${money(v)}</strong></div>`).join("")}
function renderSources(p){const counts={};(function walk(v){if(Array.isArray(v))v.forEach(walk);else if(v&&typeof v==="object"){if(v.status&&v.provider)counts[`${v.status}|${v.provider}`]=(counts[`${v.status}|${v.provider}`]||0)+1;Object.values(v).forEach(walk)}})(p);$("#sources").innerHTML=Object.entries(counts).map(([k,n])=>{const[s,provider]=k.split("|");return `<div class="source-row">${badge({status:s,provider})}<strong>${n} 项</strong></div>`}).join("")||"<p class='muted'>暂无来源数据</p>"}
function renderMap(t){const used=new Set(t.days.flatMap(d=>d.visits.map(v=>v.place_id))),pts=session.places.filter(p=>used.has(p.id)).map(p=>({id:p.id,name:p.name,lat:p.location.latitude,lon:p.location.longitude,hotel:false}));pts.unshift({id:t.lodging_area.id,name:"住宿",lat:t.lodging_area.location.latitude,lon:t.lodging_area.location.longitude,hotel:true});if(pts.length<2){$("#map").innerHTML="<p class='muted'>坐标不足</p>";return}const lats=pts.map(p=>p.lat),lons=pts.map(p=>p.lon),minLat=Math.min(...lats),maxLat=Math.max(...lats),minLon=Math.min(...lons),maxLon=Math.max(...lons),xy=p=>[50+(p.lon-minLon)/(maxLon-minLon||1)*540,290-(p.lat-minLat)/(maxLat-minLat||1)*240];const coords=pts.map(p=>xy(p).join(",")).join(" ");$("#map").innerHTML=`<svg viewBox="0 0 640 340" role="img" aria-label="行程地点示意图"><defs><pattern id="grid" width="32" height="32" patternUnits="userSpaceOnUse"><path d="M32 0H0V32" fill="none" stroke="#24302d" stroke-width="1"/></pattern></defs><rect width="640" height="340" fill="url(#grid)"/><polyline class="route-line" points="${coords}"/>${pts.map((p,i)=>{const[x,y]=xy(p);return `<circle class="point ${p.hotel?"hotel":""}" cx="${x}" cy="${y}" r="${p.hotel?8:6}"/><text x="${x+10}" y="${y+4}">${i?i+". ":""}${esc(p.name)}</text>`}).join("")}</svg>`}

function renderChat(){$("#chat").innerHTML=messages.map(m=>`<div class="message ${m.role}">${esc(m.text)}</div>`).join("");$("#chat").scrollTop=$("#chat").scrollHeight;if(session.last_diff){$("#diff").classList.remove("hidden");$("#diff").innerHTML=`<strong>本轮变化</strong><br>${session.last_diff.summary.map(esc).join("<br>")}<br><span class="muted">保留：${esc(session.last_diff.preserved_fields.join("、")||"无")}</span>`}else $("#diff").classList.add("hidden")}
function renderRuntime(){const calls=session.model_calls||[],last=calls.at(-1),tokens=calls.reduce((n,c)=>n+c.input_tokens+c.output_tokens,0);$("#modelBadge").textContent=last?`${last.mode} · ${last.model}`:"DETERMINISTIC";$("#fetchCount").textContent=`${session.data_fetch_count} 次`;$("#revisionCount").textContent=`${session.revision_count} 次`;$("#historyCount").textContent=session.history.length;$("#tokenCount").textContent=tokens;$("#timeline").innerHTML=session.events.slice().reverse().map(e=>`<div class="event">${new Date(e.created_at).toLocaleTimeString("zh-CN")} · ${esc(e.message)}</div>`).join("");loadTrace()}
async function sendRevision(text){if(!text.trim())return;messages.push({role:"user",text});renderChat();try{session=await api(`/v2/sessions/${session.id}/revise`,{method:"POST",body:JSON.stringify({text})});messages.push({role:"agent",text:"修改已应用，并再次通过确定性约束检查。"});$("#revision").value="";clearConflict();render()}catch(e){renderConflict(e.detail);messages.push({role:"agent",text:e.message});renderChat()}}
$("#revise").onclick=()=>sendRevision($("#revision").value);document.querySelectorAll("[data-prompt]").forEach(b=>b.onclick=()=>sendRevision(b.dataset.prompt));
$("#undo").onclick=async()=>{try{session=await api(`/v2/sessions/${session.id}/undo`,{method:"POST"});messages.push({role:"agent",text:"已恢复到上一版行程。"});render()}catch(e){messages.push({role:"agent",text:e.message});renderChat()}};
document.querySelectorAll(".locks input").forEach(x=>x.onchange=async()=>{const fields=[...document.querySelectorAll(".locks input:checked")].map(i=>i.value);try{session=await api(`/v2/sessions/${session.id}/locks`,{method:"PUT",body:JSON.stringify({fields})});renderRuntime()}catch(e){setStatus(e.message)}});
$("#explain").onclick=async()=>{try{const d=await api(`/v2/sessions/${session.id}/explain`,{method:"POST"}),e=d.explanation;$("#explanation").classList.remove("hidden");$("#explanation").innerHTML=`<h3>AI 行程解读</h3><p>${esc(e.summary)}</p><p>${esc(e.transport_reason)}</p><p>${esc(e.lodging_reason)}</p><p>${esc(e.budget_statement)}</p>`;session=await api(`/v2/sessions/${session.id}`);renderRuntime()}catch(e){setStatus(e.message)}};
$("#refresh").onclick=async()=>{if(!session||session.mode!=="LIVE")return;setStatus("正在刷新实时数据快照…");try{session=await api(`/v2/sessions/${session.id}/refresh`,{method:"POST"});messages.push({role:"agent",text:"实时快照已刷新，请重新选择一个方案。"});clearConflict();render();setStatus("实时数据已刷新")}catch(e){renderConflict(e.detail);setStatus(e.message)}};
$("#dataMode").onchange=()=>setStatus($("#dataMode").value==="LIVE"?"实时模式会查询高德、12306 与飞常准，并在会话内冻结结果":"离线 Fixture 模式可直接演示，无需外部 Key");

function renderSnapshot(){if(!session?.snapshot)return;const s=session.snapshot,providers=s.providers||[];$("#snapshot").innerHTML=`<div class="panel-title"><div><p class="step-label">Planning Snapshot</p><h3>${esc(s.mode)} · ${esc(s.id)}</h3></div><span class="pill">刷新 ${s.refresh_count} 次</span></div><div class="snapshot-providers">${providers.map(p=>`<div>${badge(p)}<strong>${p.item_count} 项</strong><small>${p.expired?"已过期":p.expires_at?`有效至 ${new Date(p.expires_at).toLocaleTimeString("zh-CN")}`:"会话内固定"}</small></div>`).join("")}</div>${s.fallback_reason?`<p class="warning">实时数据已降级：${esc(s.fallback_reason)}</p>`:""}`}
function clearConflict(){["#conflict","#composerConflict"].forEach(id=>{$(id).classList.add("hidden");$(id).innerHTML=""})}
function renderConflict(detail){if(!detail||typeof detail!=="object"||!detail.code)return;const suggestions=detail.suggestions||[],target=session?$("#conflict"):$("#composerConflict");target.classList.remove("hidden");target.innerHTML=`<p class="step-label">Constraint Conflict · ${esc(detail.code)}</p><h3>${esc(detail.title)}</h3><p>${esc(detail.message)}</p><div class="conflict-actions">${suggestions.map(s=>`<button data-suggestion="${esc(s.revision_text)}" class="ghost">${esc(s.label)}</button>`).join("")}</div>`;target.querySelectorAll("[data-suggestion]").forEach(b=>b.onclick=()=>{if(!b.dataset.suggestion)return;if(session)sendRevision(b.dataset.suggestion);else{$("#request").value+=`，${b.dataset.suggestion}`;setStatus("建议已加入需求，请确认预算或约束后重新生成")}})}
async function loadTrace(){if(!session)return;try{const t=await api(`/v2/sessions/${session.id}/trace`);$("#traceSummary").textContent=`${t.total_steps} 步 · ${Math.round(t.total_latency_ms)} ms`;$("#executionTrace").innerHTML=t.steps.slice().reverse().map(x=>`<div class="trace-step ${esc(x.status)}"><span>${esc(x.category)}</span><strong>${esc(x.name)}</strong><small>${esc(x.provider)} · ${Math.round(x.duration_ms)} ms${x.input_tokens+x.output_tokens?` · ${x.input_tokens+x.output_tokens} token`:""}</small></div>`).join("")}catch{$("#executionTrace").innerHTML="<p class='muted'>Trace 暂不可用</p>"}}
loadHealth();
